#!/usr/bin/env bash
set -euo pipefail

export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get install --yes --no-install-recommends \
  build-essential \
  cmake \
  fonts-noto-cjk \
  gstreamer1.0-libav \
  gstreamer1.0-gl \
  gstreamer1.0-plugins-bad \
  gstreamer1.0-plugins-base \
  gstreamer1.0-plugins-good \
  gstreamer1.0-qt6 \
  gstreamer1.0-tools \
  gstreamer1.0-x \
  libgstreamer-plugins-base1.0-dev \
  libgstreamer1.0-dev \
  libaribb24-dev \
  libclang-dev \
  libmpv-dev \
  libqt6svg6 \
  lld \
  mesa-utils \
  imagemagick \
  ninja-build \
  openbox \
  mpv \
  pkg-config \
  qml6-module-qtqml \
  qml6-module-qtqml-models \
  qml6-module-qtqml-workerscript \
  qml6-module-qtquick \
  qml6-module-qtquick-controls \
  qml6-module-qtquick-layouts \
  qml6-module-qtquick-templates \
  qml6-module-qtquick-window \
  qt6-base-dev \
  qt6-declarative-dev \
  qt6-l10n-tools \
  qt6-svg-plugins \
  qt6-wayland \
  x11-utils \
  xdotool \
  xvfb
